### ISSUE TITLE
Folder is exists

### ISSUE THREAD

**Issue by StGeass** [rambler-digital-solutions/rship#10]
Cannot create new boilerplate app

```
$> rship new test
22:08:07 App will create at: /path/test
22:08:07 Error: Folder '/path/test' is exists
```
App folder is empty, macOS 10.12.1, node v7.2.1

**Comment by mrsum** [comment]
@StGeass Well, ```/path/test``` is exists or not?

**Comment by mrsum** [comment]
@StGeass so, fixed in 1.0.10

**Comment by mrsum** [comment]
Reopen, if something will go wrong

**Comment by StGeass** [comment]
@mrsum Сhecked at self, everything is ok too
